from tkinter import *
from mysql import *
import tkinter
import mysql.connector as mysql
root = Tk()
tkvar = StringVar(root)
def form1():
    root1=Tk()
    label=tkinter.Label(root1,text="User tittle",font=("Helvetica", 15))
    label.place(x=50,y=50)
    n1=["Mr"]
    n2=["Ms"]
    n3=["Dr"]
    n4=["Miss"]
    clicked=StringVar()
    drop=OptionMenu(root1,clicked,n1,n2,n3,n4)
    drop.place(x=185,y=50)
    def change_dropdown(*args):
         print( clicked.get() )
    clicked.trace('w', change_dropdown)
    label1=tkinter.Label(root1,text="User name",font=("Helvetica", 15))
    label1.place(x=50,y=100)
    entry=tkinter.Entry(root1)
    entry.place(x=185,y=108)
    label2=tkinter.Label(root1,text="User Age",font=("Helvetica", 15))
    label2.place(x=50,y=150)
    entry1=tkinter.Entry(root1)
    entry1.place(x=185,y=158)
    label3=tkinter.Label(root1,text="Interest in college subject",font=("Helvetica", 15))
    label3.place(x=50,y=208)
    cbutton=tkinter.Checkbutton(root1,text="Enterprise java")
    cbutton.place(x=50,y=240)
    cbutton1=tkinter.Checkbutton(root1,text="Linux")
    cbutton1.place(x=50,y=260)
    cbutton2=tkinter.Checkbutton(root1,text="IOT")
    cbutton2.place(x=50,y=280)
    cbutton3=tkinter.Checkbutton(root1,text="AWP")
    cbutton3.place(x=50,y=300)
    cbutton2=tkinter.Checkbutton(root1,text="SPM")
    cbutton2.place(x=50,y=320)
    label4=tkinter.Label(root1,text="Interested in Music",font=("Helvetica", 15))
    label4.place(x=50,y=370)
    var=StringVar()
    rbutton=tkinter.Radiobutton(root1,text="Yes",variable=var,value ="")
    rbutton.place(x=235,y=375)
    rbutton1=tkinter.Radiobutton(root1,text="No",variable=var,value ="")
    rbutton1.place(x=295,y=375)
    b3=tkinter.Button(root1,text='Submit',height=3, width=19,command="")
    b3.place(x=50,y=420)
    b4=tkinter.Button(root1,text='Form2',height=3, width=19,command=form2)
    b4.place(x=50,y=480)
    
    root1.mainloop()
    
    
def form2():
    root2=Tk()
    label5=tkinter.Label(root2,text="Enetr 10th marks",font=("Helvetica", 15))
    label5.place(x=50,y=100)
    entry3=tkinter.Entry(root2)
    entry3.place(x=220,y=108)
    label6=tkinter.Label(root2,text="Enetr 12th marks",font=("Helvetica", 15))
    label6.place(x=50,y=150)
    entry4=tkinter.Entry(root2)
    entry4.place(x=220,y=158)
    label7=tkinter.Label(root2,text="Enetr Graduation marks",font=("Helvetica", 15))
    label7.place(x=50,y=200)
    entry5=tkinter.Entry(root2)
    entry5.place(x=280,y=208)
    label8=tkinter.Label(root2,text="Enetr Post Graduation marks",font=("Helvetica", 15))
    label8.place(x=50,y=250)
    entry6=tkinter.Entry(root2)
    entry6.place(x=315,y=258)
    label9=tkinter.Label(root2,text="others Examination name",font=("Helvetica", 15))
    label9.place(x=50,y=300)
    entry7=tkinter.Entry(root2)
    entry7.place(x=305,y=308)
    label9=tkinter.Label(root2,text="others Examination marks",font=("Helvetica", 15))
    label9.place(x=50,y=350)
    entry8=tkinter.Entry(root2)
    entry8.place(x=305,y=358)
    b5=tkinter.Button(root2,text='Submit',height=3, width=19,command="")
    b5.place(x=50,y=420)
    b6=tkinter.Button(root2,text='Form1',height=3, width=19,command=form1)
    b6.place(x=50,y=480)

l=tkinter.Label(root,text="Select the Any Form Frist",font=("Helvetica", 19,"bold"))
l.place(x=600,y=100)
b1=tkinter.Button(root,text='Form 1',height=3, width=19,command=form1)
b1.place(x=600,y=200)
b2=tkinter.Button(root,text='Form 2',height=3, width=19,command=form2)
b2.place(x=755,y=200)


root.mainloop()
